spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:

  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret:
    key: U3BhcnRhQ29kaW5nY2x1YkJ1czEwQm9hcmRDUlVEU2VydmljZQ==